apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.deploymentName }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.backend.deploymentName }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: {{ printf `{"default": "%s"}` .Values.backend.deploymentName | squote }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.backend.deploymentName }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servingPort }}
      targetPort: {{ .Values.backend.servingPort }}
