{{- if and (eq .Values.frontend.servingMethod "gateway") }}
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.frontend.deploymentName }}
  namespace: {{ .Release.Name }}
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
{{ end }}