apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.deploymentName }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.frontend.deploymentName }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: {{ .Values.frontend.deploymentName }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servingPort }}
      targetPort: 80
