apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.deploymentName }}
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.deploymentName }} 
  serviceName: {{ .Values.db.deploymentName }}
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Values.db.deploymentName }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.db.deploymentName }}
        image: {{ .Values.db.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.deploymentName }}-password
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: {{ .Values.db.deploymentName }}
        volumeMounts:
        - name: {{ .Values.db.deploymentName }}-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.db.deploymentName }}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: {{ .Values.db.storageSize }}
